# Site settings
title: "Olive2Oil"
email: macorlett@gmail.com
description: "Gold Medail winning Extra Virgin Olive Oil at its finest, grown right here in New Zealand."
baseurl: ""
url: "http://127.0.0.1" # the base hostname & protocol for your site
port: 4000
twitter: ""
dribbble: ""

# Build settings
# paginate: 10
markdown: rdiscount
permalink: pretty
sass:
style: :compressed
